[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ferris-says = "0.3.1"
# cargo-generate = "0.18.4"
# wasm-pack = "0.12.0"
rocket = "=0.5.0-rc.3"

[dev-dependencies]

